import os
import json
import asyncio
import google.auth
from google.adk.agents import Agent, SequentialAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.apps import App
from google.adk.models import Gemini
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from pydantic import BaseModel, Field
from typing import Literal

# Environment setup for Vertex AI vs AI Studio
if os.environ.get("GEMINI_API_KEY"):
    os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "False"
    os.environ["GOOGLE_API_KEY"] = os.environ.get("GEMINI_API_KEY")
else:
    try:
        _, project_id = google.auth.default()
        os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
        os.environ["GOOGLE_CLOUD_LOCATION"] = "global"
        os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"
    except Exception:
        os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "False"

# Pydantic schema for structured exercise block
class WorkoutBlock(BaseModel):
    title: str = Field(description="Title of the exercise block (e.g. 'Warm-up Drills')")
    distance: int = Field(description="Distance in meters (e.g. 400)")
    time: int = Field(description="Duration of the block in minutes (e.g. 20)")
    category: Literal["warmup", "drills", "mainset", "sprint", "cooldown"] = Field(description="The category of the block")
    details: str = Field(description="Specific instructions (e.g. '4x100m Medley | Easy Pace')")
    description: str = Field(description="Short description of the focus (e.g. 'Focus on form')")
    tags: list[str] = Field(description="A list of tags (e.g. ['Drills', 'Warmup'])")

# Pydantic schema for full workout plan
class SwimWorkoutPlan(BaseModel):
    blocks: list[WorkoutBlock] = Field(description="Ordered list of training blocks making up the workout plan")

# MCP client communication helper
async def call_mcp_tool(name: str, arguments: dict = None) -> dict:
    server_params = StdioServerParameters(
        command="uv",
        args=["run", "python", "-m", "app.mcp_server"],
    )
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool(name, arguments or {})
            # Extract content from result
            if not result.content or len(result.content) == 0:
                raise ValueError(f"No content returned from tool {name}")
            content = result.content[0].text
            return json.loads(content)

# Async tool functions that talk to the MCP server
async def get_swim_templates() -> list[dict]:
    """Get the standard swim exercise templates available in SwimmPlan Smart.
    
    Use this tool to find standard exercises (like warm-ups, sprints, cooldowns)
    to reuse or adapt for the training plan.
    """
    return await call_mcp_tool("get_swim_templates")

async def get_coaching_guidelines() -> dict:
    """Get the official coaching guidelines for creating a balanced swim training plan.
    
    Use this tool to learn the rules of structured workouts (warm-up first, cooldown last,
    total duration limit, etc.) so that the workout conforms to the coach's guidelines.
    """
    return await call_mcp_tool("get_coaching_guidelines")

# 1. Generator Agent (Uses MCP tools to draft plan in text)
generator_agent = Agent(
    name="generator_agent",
    model=Gemini(
        model="gemini-2.5-flash",
    ),
    instruction="""You are an expert swim coach assistant. Your job is to create a structured swim training plan based on the coach's request.
First, call the MCP tools to retrieve the standard swim templates (`get_swim_templates`) and coaching guidelines (`get_coaching_guidelines`).
Then, design a workout plan. It MUST follow the coaching guidelines (e.g. warm-up first, cooldown last, total duration <= 120 mins).
Ensure you list the training blocks in order, specifying details (title, distance in meters, duration in minutes, category, details, description, tags) for each block.
Coach Request: {user_prompt}""",
    tools=[get_swim_templates, get_coaching_guidelines],
    output_key="draft_plan",
)

# 2. Validator / Parser Agent (Enforces rules and outputs structured JSON)
validator_agent = Agent(
    name="validator_agent",
    model=Gemini(
        model="gemini-2.5-flash",
    ),
    instruction="""You are a swimming workout validator.
Your input is the draft plan generated by the workout creator.
You MUST:
1. Examine the draft plan.
2. Ensure it starts with a warmup block. If not, add one using standard warmup templates.
3. Ensure it ends with a cooldown block. If not, add one using standard cooldown templates.
4. Ensure the total duration is between 30 and 120 minutes. If it exceeds 120 minutes, scale down some durations.
5. Parse this verified plan strictly into the SwimWorkoutPlan output schema.
6. The coach's initial query was: {user_prompt}
7. The draft plan is: {draft_plan}""",
    output_schema=SwimWorkoutPlan,
    output_key="final_plan",
)

# Callback to initialize state and extract user prompt
async def init_state(callback_context: CallbackContext) -> None:
    session = callback_context.session
    user_prompt = ""
    events = session.events or []
    for event in reversed(events):
        author = getattr(event, "author", None) or (event.get("author") if isinstance(event, dict) else None)
        if author == "user":
            content = getattr(event, "content", None) or (event.get("content") if isinstance(event, dict) else None)
            if content:
                parts = getattr(content, "parts", None) or (content.get("parts") if isinstance(content, dict) else None)
                if parts and len(parts) > 0:
                    part = parts[0]
                    text = getattr(part, "text", None) or (part.get("text") if isinstance(part, dict) else None)
                    if text:
                        user_prompt = text
                        break
    callback_context.state["user_prompt"] = user_prompt or "Create a balanced workout"

# 3. Sequential pipeline combining Generator and Validator
workout_pipeline = SequentialAgent(
    name="workout_pipeline",
    sub_agents=[generator_agent, validator_agent],
    before_agent_callback=init_state,
)

# Define the ADK application
app = App(
    root_agent=workout_pipeline,
    name="app",
)
